### ISSUE TITLE
How to ignore an attribute on a particular model?

### ISSUE THREAD

**Issue by amelkikh** [somnambulist-tech/laravel-doctrine-entity-audit#1]
Hi!
So, question in title.
I can't use global attribute because of this attribute has several models.
Thx

**Comment by dave-redfern** [comment]
It is not possible to ignore specific attributes on a single model on an entity manager.

However: ignores can be set on each entity manager definition by adding the ignore_columns key. If you can use multiple entity managers (pretty complex task to be honest), you could then set the ignored columns by entity manager.
