### ISSUE TITLE
Multiple issues with revision generation

### ISSUE THREAD

**Issue by Rezaldy** [somnambulist-tech/laravel-doctrine-entity-audit#3]
Hi! Sorry to bother you with more questions/requests. We have run into 2 issues that are blocking us from making progress.

**Custom timestamp class**
We use a custom DateTime type and Entity, where the entity is an extension of the default DateTime class. When LDEA tries to execute the `convertToDatabaseValue` on the DateTime Type, it fails because the `$value` passed to the function is also a Type class, not a Doctrine Entity class and our Type class tries to run a method that is only available on the Entity class.

My question is; is it possible to pass the timestamp through the entity manager's config? For example;

```php
[
    'entity_managers' => [
        'default' => [
            'entities' => [
                // Some/Entity/Classname::class,
                // Default sales entities
            ],
           //
           'timestamp' => new \Our\Custom\Entity\DateTime,
        ],
    ],
]
```
and to then have the LogRevisionsListener pick this up if it's set? 

**UserResolver user interfaces**
In order to get the user's identifier, we need to implement one of four interfaces defined by the package;

- UniversallyIdentifiable
- Authenticatable
- Identifiable
- Nameable

Authenticatable is one of Laravel's default Contracts, but it asks me to implement additional method stubs that we will never be using.

UniversallyIdentifiable, Identifiable and Nameable come from the `somnambulist/laravel-doctrine-behaviours` package. This package is however outdated, and if my research is correct it is replaced by the `somnambulist/domain` package. Domain however is a package that would require us to upgrade to a later version of Laravel even at its earlier versions (We're stuck to ramsey/uuid 3.4 right now). Since we cannot upgrade until Laravel 9 LTS comes out, we're in a bit of a pickle. Is it possible for the config to allow us to either specify what identification method/function to use, OR what interface it needs to check for?

**Comment by Rezaldy** [comment]
FYI; I'm okay with the `domain` interfaces and I think I can work out something to upgrade to Laravel 8 anyways so if you want to say you won't fix that, that's totally fine by me, but I did run into that DateTime issue and that is a bit more blocking right now.. Just a note in terms of priority. :)

**Comment by dave-redfern** [comment]
@Rezaldy 
Re: datetime issue: in theory, so long as your type is registered with Doctrines type system it should be fine as it will pull that information from the registered type data. e.g.: you register your `DateTime` class as the type: `datetime` instead of Doctrines built-in version. If it is not registered, then yeah it may not convert well. It sounds like it is maybe not registered or the type is not set on the mapping information?? Hard to say. I've not had an issue with my own custom types.

Re: UserResolver: yeah - my bad! I've not updated that component in quite a while and how I use those things has changed a lot. I would not recommend switching to the domain library in your case. Tell you what, I'll make a refactor so that the UserResolver can be more easily replaced, then you can implement your own resolver logic for your needs. The original will just be a default implementation. It will take me a little while to get to that, but maybe later today / tomorrow (Wed May 19th 2021).

**Comment by Rezaldy** [comment]
@dave-redfern  I have a solution for the user issue where our user entity is just implementing the Authenticatable interface from Laravel, and we just see the empty stubs as a "necessary evil" we can ignore. If you still want to do what you said, that is fine! I think we'll be able to work with the Authenticatable interface though.

When it comes to the datetime issue, I do have it registered as a custom type, but somehow it still does this. I have a branch made locally with a possible solution, but I don't know if it clashes with your idea. I think it'd also allow people to use their own (third party) package to generate a datetime value too (Although it is probably niche).

```diff
diff --git a/config/entity_audit.php b/config/entity_audit.php
index 9629915..351ad12 100644
--- a/config/entity_audit.php
+++ b/config/entity_audit.php
@@ -93,6 +93,7 @@ return [
      *     'entities' => [],
      *     'table' => [
      *         'table_suffix' => '',
+     *         'timestamp' => new \Your\Custom\DateTime('now'),
      *     ],
      *     'username_for => [
      *
diff --git a/src/AuditConfiguration.php b/src/AuditConfiguration.php
index 1799f5d..e7dde96 100644
--- a/src/AuditConfiguration.php
+++ b/src/AuditConfiguration.php
@@ -151,4 +151,13 @@ class AuditConfiguration
     {
         return $this->tableConfig->getRevisionTableName();
     }
+
+    /**
+     * @return string
+     */
+    public function getTimestamp()
+    {
+        return $this->tableConfig->getTimestamp();
+    }
+
 }
diff --git a/src/EventListener/LogRevisionsListener.php b/src/EventListener/LogRevisionsListener.php
index 1331c08..155504f 100644
--- a/src/EventListener/LogRevisionsListener.php
+++ b/src/EventListener/LogRevisionsListener.php
@@ -308,7 +308,7 @@ class LogRevisionsListener implements EventSubscriber
             $this->conn->insert(
                 $this->config->getRevisionTableName(),
                 [
-                    'timestamp' => date_create('now'),
+                    'timestamp' => $this->config->getTimestamp(),
                     'username'  => $this->config->getCurrentUsername(),
                 ],
                 [
diff --git a/src/Support/TableConfiguration.php b/src/Support/TableConfiguration.php
index 6e2e4bd..d226d45 100644
--- a/src/Support/TableConfiguration.php
+++ b/src/Support/TableConfiguration.php
@@ -130,4 +130,12 @@ class TableConfiguration
     {
         return $this->get('revision_id_field_type', 'bigint');
     }
+
+    /**
+     * @return string
+     */
+    public function getTimestamp()
+    {
+        return $this->get('timestamp', date_create('now'));
+    }
 }
```

**Comment by dave-redfern** [comment]
That is setting the datetime of the revision itself to a single datetime instance that would be set at request time, not at the time of the modification itself. For long running processes e.g. CLI, swoole or PHPPM, that would mean every revision would get the same datetime for every revision.

**Comment by dave-redfern** [comment]
@Rezaldy 0.7.0 just pushed and tagged adds a `UserResolverInterface`. You can implement your own version that does exactly what you need. Either register this in your AppServiceProvider, or change the instance on the AuditRegistry (can be done on boot or afterResolving).

**Comment by Rezaldy** [comment]
@dave-redfern
> That is setting the datetime of the revision itself to a single datetime instance that would be set at request time, not at the time of the modification itself. For long running processes e.g. CLI, swoole or PHPPM, that would mean every revision would get the same datetime for every revision.

Oh.. Darn it, I just noticed this yeah, it really does that for me on my docker instance. Uhm.. So then.. What about providing a `timestamp_class` through the config, and then having the AuditConfiguration generate a DateTime, like a "factory method" kinda thing?

I'll try out the UserResolverInterface, thank you!

**Comment by Rezaldy** [comment]
So like this, maybe..?

```diff
diff --git a/config/entity_audit.php b/config/entity_audit.php
index 9629915..4fa3306 100644
--- a/config/entity_audit.php
+++ b/config/entity_audit.php
@@ -93,6 +93,7 @@ return [
      *     'entities' => [],
      *     'table' => [
      *         'table_suffix' => '',
+     *         'timestamp_class' => \Your\Custom\DateTime::class
      *     ],
      *     'username_for => [
      *
diff --git a/src/AuditConfiguration.php b/src/AuditConfiguration.php
index 8e4ab88..01aa077 100644
--- a/src/AuditConfiguration.php
+++ b/src/AuditConfiguration.php
@@ -159,4 +159,13 @@ class AuditConfiguration
     {
         return $this->tableConfig->getRevisionTableName();
     }
+
+    /**
+     * @return string
+     */
+    public function getTimestamp()
+    {
+        return $this->tableConfig->getTimestamp();
+    }
+
 }
diff --git a/src/EventListener/LogRevisionsListener.php b/src/EventListener/LogRevisionsListener.php
index 1331c08..857ecec 100644
--- a/src/EventListener/LogRevisionsListener.php
+++ b/src/EventListener/LogRevisionsListener.php
@@ -308,7 +308,7 @@ class LogRevisionsListener implements EventSubscriber
             $this->conn->insert(
                 $this->config->getRevisionTableName(),
                 [
-                    'timestamp' => date_create('now'),
+                    'timestamp' => $this->config->getTimestamp(),
                     'username'  => $this->config->getCurrentUsername(),
                 ],
diff --git a/src/Support/TableConfiguration.php b/src/Support/TableConfiguration.php
index 6e2e4bd..82bea2d 100644
--- a/src/Support/TableConfiguration.php
+++ b/src/Support/TableConfiguration.php
@@ -130,4 +130,13 @@ class TableConfiguration
     {
         return $this->get('revision_id_field_type', 'bigint');
     }
+
+    /**
+     * @return string
+     */
+    public function getTimestamp()
+    {
+        $timestampClass = $this->get('timestamp_class', '');
+        return $timestampClass ? new $timestampClass('now') : date_create('now');
+    }
 }
```

**Comment by dave-redfern** [comment]
@Rezaldy So the issue is that `date_create()` returns a standard DateTime instance that then cannot be handled by your overridden `datetime` type? In that case does this change work:
```
index 1331c08..4f9f93b 100644
--- a/src/EventListener/LogRevisionsListener.php
+++ b/src/EventListener/LogRevisionsListener.php
@@ -308,7 +308,7 @@ class LogRevisionsListener implements EventSubscriber
             $this->conn->insert(
                 $this->config->getRevisionTableName(),
                 [
-                    'timestamp' => date_create('now'),
+                    'timestamp' => Type::getType('datetime')->convertToPHPValue('now', $this->platform),
                     'username'  => $this->config->getCurrentUsername(),
                 ],
                 [
```
Instead of passing through config, it just uses the type itself and builds a datetime by passing through "now" to the convertToPHPValue method. I've added a test that appears to work with this, but it does rely on the type being able to handle "now" in the createFromFormat() method.

**Comment by Rezaldy** [comment]
@dave-redfern Works like a charm when I test that with our custom entity.

**Comment by dave-redfern** [comment]
@Rezaldy Alright! I shall update and tag a new version with that patch.

**Comment by Rezaldy** [comment]
@dave-redfern Great! Thank you so much Dave!

**Comment by dave-redfern** [comment]
0.7.1 tagged with this.
