### ISSUE TITLE
Doctrine types not always(?) passed correctly

### ISSUE THREAD

**Issue by Rezaldy** [somnambulist-tech/laravel-doctrine-entity-audit#4]
Hi! Sorry to bug you again @dave-redfern.

We noticed that at some point, some types fall off and aren't sent correctly. My coworker noticed that when the following like is added under LogRevisionsListener.php:153
```php
$types[] = $targetTable->getTypeOfColumn($definition['referencedColumnName']);
```

it's fixed. I don't have a direct example of this happening, but the `$types` array has only 2 variables where it should have been 3 on one of our entities, the third entity is `null`. This could possibly be the wrong solution, but I think it was worth noting.

**Comment by dave-redfern** [comment]
@Rezaldy When I made this library, I ported the code largely as-is from the original SimpleThings bundle. Looking at the code in that section around ln 153, those variables are set and then never used anywhere, so it's entirely possible that this is a long standing bug.

I am more than happy to add that as a bug fix, but no idea if there would be any knock-on consequences.

If you could provide an example I can add as a test case, that would be greatly appreciated!

**Comment by Rezaldy** [comment]
I don't know how to give a concise and clear example right now, I guess I only found out because there was a query that was something along the lines of

```sql
UPDATE revision_audit_contractedproduct SET status_id = ? WHERE rev = ? AND id = ?
```

And it had types and params passed to it in the initial query, where one of the types wasn't present in the postFlush types. Apparently it's specifically when there is joincolumns present in the query's associationmappings.

The types array at first was looking like;
```php
[
    'uuid',
    'bigint',
    'uuid'
]
```

with params looking like;
```php
[
    UUID class here,
    25,
    UUID class here,
]
```

But in postFlush at the end, the types array suddenly looks like; 
```php
[
    'bigint',
    'uuid',
    null
]
```

As if it couldn't add the type of the `status_id` field and then pads the array with a null value so that the amount of types matches the amount of query parameters. Maybe good to note; This `status_id` field in our case is not a flat value but a foreign key referring to a record in a different table.

**Comment by dave-redfern** [comment]
@Rezaldy hmm, OK. If you are happy to be a guinea pig, I can make the change and push and then you can run dev-master for a bit. If you don't find any weirdness after a few days, I'll tag another point release. Does that sound reasonable?

**Comment by Rezaldy** [comment]
@dave-redfern Hit me with it! :)

**Comment by dave-redfern** [comment]
@Rezaldy pushed to master!

**Comment by Rezaldy** [comment]
@dave-redfern Hi dave, thank you! dev-master works smoothly so far! I did overlook the fact we can just use

```php
$types[] = $type;
```

Instead.. Would make sense since you already fetched the type on the line right above it.. But yeah, so far I see no more errors on any of the entities I've tried to track!

**Comment by dave-redfern** [comment]
@Rezaldy true enough! I had considered that and will make that change and tag a release.

**Comment by dave-redfern** [comment]
@Rezaldy I've tagged 0.7.2 with this fix. Thanks for reporting and help debugging!
